# Generated by Django 3.1.4 on 2021-04-01 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quanity',
            new_name='quantity',
        ),
    ]
